//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z3nth10n_Launcher.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("z3nth10n_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap dirt {
            get {
                object obj = ResourceManager.GetObject("dirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] MBold {
            get {
                object obj = ResourceManager.GetObject("MBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] MBoldItalic {
            get {
                object obj = ResourceManager.GetObject("MBoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Minecraft {
            get {
                object obj = ResourceManager.GetObject("Minecraft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Minecraft1 {
            get {
                object obj = ResourceManager.GetObject("Minecraft1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] MItalic {
            get {
                object obj = ResourceManager.GetObject("MItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] MRegular {
            get {
                object obj = ResourceManager.GetObject("MRegular", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
